246 update dates on current point in the recruitment cycle page
DFE-Digital/find-teacher-training pull request #1413
Opened 2022-07-25 11:57 UTC by avinhurry

### Context

### Changes proposed in this pull request

### Guidance to review

### Trello card

### Checklist

- [ ] Rebased `main`
- [ ] Cleaned commit history
- [ ] Tested by running locally

2022-07-25 12:09 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update dates on Current point in the recruitment cycle page](https://trello.com/c/7FoKmr6z/246-update-dates-on-current-point-in-the-recruitment-cycle-page)

2022-07-26 09:14 UTC, defong requested changes

2022-07-26 09:14 UTC, defong commented on app/helpers/current_point_in_recruitment_cycle_helper.rb
> +    "#{I18n.t('cycles.today_is_after_find_opens.description')} (#{CycleTimetable.find_opens.next_year.to_formatted_s(:govuk_date)})"
```suggestion
    "#{I18n.t('cycles.today_is_after_find_opens.description')} (#{CycleTimetable.find_reopens.next_year.to_formatted_s(:govuk_date)})"
```

2022-07-26 09:27 UTC, avinhurry commented on app/helpers/current_point_in_recruitment_cycle_helper.rb
> +    "#{I18n.t('cycles.today_is_after_find_opens.description')} (#{CycleTimetable.find_opens.next_year.to_formatted_s(:govuk_date)})"
perfect, thanks. That felt a bit wrong

2022-07-26 10:58 UTC, defong approved these changes

2022-07-26 11:07 UTC, merged