Update results page ordering options
DFE-Digital/find-teacher-training pull request #1681
Opened 2023-01-16 18:10 UTC by avinhurry

### Context

We are adding the ability to sort the results page on Find by course name.

### Changes proposed in this pull request

- **Add course ordering (A-Z)**

If identical course, ordering falls back to the provider, if identical providers, ordering falls back to the course code

- **Add course ordering (Z-A)**

If identical course, ordering falls back to the provider, if identical providers, ordering falls back to the course code

- **Update provider ordering (A-Z)**

If identical provider, ordering falls back to the course, if identical courses, ordering falls back to the course code

- **Update provider ordering (Z-A)**

If identical provider, ordering falls back to the course, if identical courses, ordering falls back to the course code

### Guidance to review

Search for a few courses and check that the hierarchy above is correct.

### Trello card

https://trello.com/c/QrMrqrVS/897-sort-courses-by-course-name-find

### Checklist

- [ ] Rebased `main`
- [ ] Cleaned commit history
- [ ] Tested by running locally

2023-01-16 18:14 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sort courses by course name (Find)](https://trello.com/c/QrMrqrVS/897-sort-courses-by-course-name-find)

2023-01-19 10:55 UTC, defong requested changes

2023-01-19 10:55 UTC, defong commented on app/view_objects/results_view.rb
> +                                    .order(order: :asc)
```suggestion
                                    .order(name: :asc)
```

2023-01-19 10:55 UTC, defong commented on app/view_objects/results_view.rb
> +                                    .order(order: :asc)
```suggestion
                                    .order(name: :asc)
```

2023-01-19 11:39 UTC, avinhurry commented on app/view_objects/results_view.rb
> +                                    .order(order: :asc)
Done

https://github.com/DFE-Digital/find-teacher-training/pull/1681/commits/74aa6867a9a77530b4411cd84f9275f48ffc5ad8

https://github.com/DFE-Digital/publish-teacher-training/pull/3247/commits/f49bdf2c1b2c0a2db8c50fcaa94f1ff0d6a42dc9

2023-01-19 11:39 UTC, avinhurry commented on app/view_objects/results_view.rb
> +                                    .order(order: :asc)
Done

https://github.com/DFE-Digital/find-teacher-training/pull/1681/commits/74aa6867a9a77530b4411cd84f9275f48ffc5ad8

https://github.com/DFE-Digital/publish-teacher-training/pull/3247/commits/f49bdf2c1b2c0a2db8c50fcaa94f1ff0d6a42dc9

2023-01-19 11:51 UTC, defong approved these changes

2023-01-19 13:08 UTC, merged