Update 503 page content
DFE-Digital/find-teacher-training pull request #1690
Opened 2023-01-20 18:54 UTC by avinhurry

### Context

Update 503 page content

### Trello card

https://trello.com/c/T42G3Stf/959-update-error-pages

### Checklist

- [ ] Rebased `main`
- [ ] Cleaned commit history
- [ ] Tested by running locally

2023-01-20 18:59 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update error pages](https://trello.com/c/T42G3Stf/959-update-error-pages)

2023-01-24 10:19 UTC, defong requested changes

2023-01-24 10:19 UTC, defong commented on app/views/pages/maintainance.html.erb
> +      <p class="govuk-body">If you have any questions, email
```suggestion
      <p class="govuk-body">If you have any questions, email<br>
```

2023-01-24 10:43 UTC, avinhurry commented on app/views/pages/maintainance.html.erb
> +      <p class="govuk-body">If you have any questions, email
https://media.giphy.com/media/3ysWy6sZSv6n6HYLPf/giphy.gif

2023-01-24 11:19 UTC, merged