Update README with information about End of Cycle feature flags
DFE-Digital/find-teacher-training pull request #428
Opened 2020-09-04 08:26 UTC by TobyRet

### Context
There are three feature flags relating to the end of cycle process. 

### Changes proposed in this pull request
Update README with instructions on how to toggle End of Cycle feature flags locally and on a deployed environment

### Guidance to review

### Trello card
https://trello.com/c/38YrjNzp/2079-add-information-about-end-of-cycle-feature-flags-to-readme

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally
- [ ] Product review

2020-09-07 12:02 UTC, paulrobertlloyd requested changes
Just a few copy and markdown syntax tweaks, but otherwise all makes sense to me 😀

2020-09-07 12:02 UTC, paulrobertlloyd commented on README.md
> +Turning this flag off removes the 'apply for this course button' on each course listing.
```suggestion
Turning this flag off removes the ‘Apply for this course button’ on each course listing.
```

2020-09-07 12:02 UTC, paulrobertlloyd commented on README.md
> +#### 3. 'Cycle has ended' interim page
```suggestion
### Enable ‘Cycle has ended’ interim page 
```

2020-09-07 12:02 UTC, paulrobertlloyd commented on README.md
> +Turning this flag on redirects all home, search, results and course page requests to '/cycle-has-ended'.
```suggestion
Turning this flag on redirects all home, search, results and course page requests to `/cycle-has-ended`.
```

2020-09-07 12:02 UTC, paulrobertlloyd commented on README.md
> +```
```suggestion
```yaml
```

2020-09-07 14:29 UTC, paulrobertlloyd commented
@TobyRet Any reason for not using smart quotes? (Pet peeve!)

2020-09-08 08:13 UTC, TobyRet commented
> @TobyRet Any reason for not using smart quotes? (Pet peeve!)

I've never been asked to follow this convention before. Makes sense though - have made the  changes.
Is there a style guide I'm not aware of?

2020-09-08 09:21 UTC, paulrobertlloyd commented
I’m not sure if there’s any style mandated in a GOV.UK style guide (if not, there should be), and too many services get it wrong, but it’s really just a case of using the right characters – using ‘dumb quotes’ is a bit like using `O` in place of `0`. This is a good summary: <https://smartquotesforsmartpeople.com>

2020-09-08 09:21 UTC, paulrobertlloyd approved these changes

2020-09-08 14:41 UTC, TobyRet commented
> https://smartquotesforsmartpeople.com

Great link - thanks @paulrobertlloyd

2020-09-08 14:41 UTC, merged