Add the location table back in for courses with multiple locations
DFE-Digital/find-teacher-training pull request #740
Opened 2021-04-22 16:11 UTC by davidgisbey

### Context

We're adding back in the locations table for courses with multiple sites.

### Changes proposed in this pull request

### Guidance to review

This sits behind the ucas_only_locations feature flag, as when that is switched on the locations render in the Apply section as before.

We should remove that flag.
### Trello card

### Checklist

- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally

2021-04-23 09:38 UTC, TobyRet approved these changes
LGTM

2021-04-23 11:22 UTC, paulrobertlloyd requested changes

2021-04-23 11:22 UTC, paulrobertlloyd commented on app/views/courses/_about_schools.html.erb
> +    <% if FeatureFlag.active?(:ucas_only_locations) && course.has_vacancies? && course.site_statuses.map(&:site).uniq.many? %>
As mentioned.

```suggestion
    <% if FeatureFlag.active?(:ucas_only_locations) && course.site_statuses.map(&:site).uniq.many? %>
```

2021-04-23 11:22 UTC, paulrobertlloyd commented on app/views/courses/_about_schools.html.erb
> +      <h2 class="govuk-heading-m">Locations</h2>
```suggestion
      <h3 class="govuk-heading-m">Locations</h3>
```

2021-04-23 11:22 UTC, paulrobertlloyd commented on app/views/courses/_about_schools.html.erb
> +        <caption class="govuk-visually-hidden">Choose a training location - List of locations, vacancies and codes</caption>
```suggestion
        <caption class="govuk-visually-hidden">List of locations and vacancies</caption>
```

2021-04-26 09:12 UTC, davidgisbey commented
Thanks Paul. Have made the changes.

2021-04-26 09:26 UTC, paulrobertlloyd approved these changes

2021-04-27 08:29 UTC, merged