Update apply 2 deadline banner for EOC
DFE-Digital/find-teacher-training pull request #889
Opened 2021-08-19 12:10 UTC by stevehook

### Context

Change content of the apply 2 deadline banner to encourage candidates to begin their application before
find and apply reopen.

### Changes proposed in this pull request

- [x] Change content as follows:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/450843/130065759-8c77af76-36d3-4931-86b5-595950c1e8f9.png">

### Guidance to review

- Is the copy correct?
- Do the spec changes make sense?

### Trello card

https://trello.com/c/x0NPUz9I/3858-dev-edit-eoc-banner-the-one-when-apply-2-has-passed-to-include-link-to-sign-in

### Checklist

- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2021-08-19 12:23 UTC, EmmaFrith approved these changes
thanks Steve!

2021-08-19 13:29 UTC, EmmaFrith commented
has the content been added to the correct banner? it should be added to the banner that appears after the apply 2 deadline. from the files changed tab, it looks like it has been added to the banner that appears between the apply 1 and 2 deadline

2021-08-19 15:14 UTC, TobyRet requested changes
You've made the same error as me @stevehook  😆 (See https://github.com/DFE-Digital/find-teacher-training/pull/892)

These changes are supposed to be made to the cycle closed banner

2021-08-20 14:20 UTC, EmmaFrith approved these changes
thanks Steve, the content looks good - but don't rely on me for the code review haha

2021-08-20 14:25 UTC, JR-G approved these changes
Have tested locally with the switcher – all good 👍

2021-08-23 09:22 UTC, TobyRet approved these changes

2021-08-23 15:18 UTC, merged